<?php
/**
 * Created by PhpStorm.
 * User: vestin
 * Date: 7/11/17
 * Time: 6:17 PM
 */

namespace App\Providers;


use TwigBridge\ServiceProvider;

class ComposerServiceProvider extends ServiceProvider
{
    /**
     * {@inheritdoc}
     */
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }


}